# Generated by Django 3.2.4 on 2021-08-31 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybooksapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='image',
        ),
    ]
